In [1]:
import numpy as np

In [9]:
z=np.zeros(10)


In [3]:
z

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [4]:
z.shape

(10,)

In [10]:
z.shape=(10,1)
z

array([[0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.]])

In [13]:
z=np.ones(10)
type(z[0])

numpy.float64

In [16]:
z=np.empty(3)
z


array([3.43820964e+179, 1.34967951e+161, 6.18928002e+169])

In [21]:
z=np.linspace(2,10,5)

type(z[1])
z

array([ 2.,  4.,  6.,  8., 10.])

In [23]:

z=np.array([10,20])   #list inside the ndarray
z

array([10, 20])

In [36]:
a_list=[10,20,34,35,23,12,42]
z=np.array([a_list])
z

array([[10, 20, 34, 35, 23, 12, 42]])

In [38]:
type(z)

numpy.ndarray

In [39]:
b_list=[[10,21,212,21,221,31,31],[23,32,453,42,233,231,12]]
z=np.array([b_list])
z

array([[[ 10,  21, 212,  21, 221,  31,  31],
        [ 23,  32, 453,  42, 233, 231,  12]]])

In [40]:
type(z)
z.shape

(1, 2, 7)

In [42]:
# ?z  to view the properties of array
#?z.shape

In [45]:
z1=np.random.randint(200,size=6)
z1

array([145, 152,  54, 186, 102, 121])

In [46]:
z1[0]

145

In [47]:
z1[:3]

array([145, 152,  54])

In [48]:
z1[2:]

array([ 54, 186, 102, 121])

In [50]:
z1[0:2]

array([145, 152])

In [51]:
z1[-1]

121

In [63]:
z1[::-1]   #to reverse the array




array([121, 102, 186,  54, 152, 145])

In [64]:
from skimage import io
photo=io.imread('lion.jpg')
type(photo)

ImportError: cannot import name '_validate_lengths'

In [65]:
photo.shape

NameError: name 'photo' is not defined

In [67]:
import matplotlib.pyplot as plt
plt.imshow(photo)

NameError: name 'photo' is not defined

In [69]:
plt.imshow(photo[::-1])

NameError: name 'photo' is not defined

In [70]:
plt.imshow(photo[:, ::-1])

NameError: name 'photo' is not defined

In [71]:
plt.imshow(photo[50:150,150:280])

NameError: name 'photo' is not defined

In [72]:
plt.imshow(photo[::2,::2])


NameError: name 'photo' is not defined

In [73]:
photo
photo_sin=np.sin(photo)
photo_sin

NameError: name 'photo' is not defined

In [74]:
print(np.sum(photo))
print(np.prod(photo))
print(np.mean(photo))
print(np.std(photo))
print(np.var(photo))
print(np.min(photo))
print(np.max(photo))
print(np.argmin(photo))
print(np.argmax(photo)

SyntaxError: unexpected EOF while parsing (<ipython-input-74-28be5d326d16>, line 9)

In [75]:
z=np.array([1,2,3,4,5])
z<3

array([ True,  True, False, False, False])

In [76]:
z>3

array([False, False, False,  True,  True])

In [78]:
z[z<5]

array([1, 2, 3, 4])

In [79]:
photo_masked=np.where(photo>100, 255 ,0)  #if its greater than 100 then will replace with 255 else 0


NameError: name 'photo' is not defined

In [80]:
plt.imshow(photo_masked)

NameError: name 'photo_masked' is not defined

In [87]:
a_array=np.array([1,2,3,5,12,32,123])
b_array=np.array([11,21,21,21,32,324,2432])

In [88]:
a_array+b_array

array([  12,   23,   24,   26,   44,  356, 2555])

In [89]:
a_array+30

array([ 31,  32,  33,  35,  42,  62, 153])

In [91]:
a_array * b_array

array([    11,     42,     63,    105,    384,  10368, 299136])

In [92]:
a_array *10

array([  10,   20,   30,   50,  120,  320, 1230])

In [93]:
a_array @ b_array   #dot product of two array

310109

In [96]:
plt.imshow(photo[:,:,0].T)  #it interchanges rows and columns i.e landscape to portrait

NameError: name 'photo' is not defined

In [97]:
x=np.array([2,1,4,3,5])
np.sort(x)

array([1, 2, 3, 4, 5])


# Insofea Numpy



In [2]:
import numpy as np
list1 = [1,2,3,4,5]
numpy_arr1 = np.array(list1)
print(numpy_arr1)

[1 2 3 4 5]


In [3]:
list2 = [6,7,8,9,10]
numpy_array2=np.array(list2)
print(numpy_array2)

[ 6  7  8  9 10]


In [4]:
list1+list2

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [11]:
arr1=np.array(list1)
arr2=np.array(list2)
c=arr1+arr2
print(c)

[ 7  9 11 13 15]


In [15]:
print(list(map(lambda x,y:x+y, list1,list2)))

[7, 9, 11, 13, 15]


In [16]:
type(c)

numpy.ndarray

In [26]:
# list comprehension to find the less or greater numbers in alist

a=[1,2,3,4,5,6,7,1]

result =[i for i in a if i < 4]
print(result)

[1, 2, 3, 1]


In [40]:
#Two dimensional array
num_2_dim=np.array([
                    [1,2,3],
                    [2,3,4,]
                    ])

In [41]:
print(num_2_dim)

[[1 2 3]
 [2 3 4]]


In [42]:
print(num_2_dim.shape)

(2, 3)


In [45]:
num_2_dim.reshape(3,2)

array([[1, 2],
       [3, 2],
       [3, 4]])

In [47]:
lin_arr = np.linspace(10,20,15) #The linspace() function returns numbers evenly spac
#ed over a specified intervals
lin_arr
# 15 values betweem 10 and 20

array([10.        , 10.71428571, 11.42857143, 12.14285714, 12.85714286,
       13.57142857, 14.28571429, 15.        , 15.71428571, 16.42857143,
       17.14285714, 17.85714286, 18.57142857, 19.28571429, 20.        ])

In [50]:
diagonal=np.eye(4)
diagonal

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [53]:
zero=np.zeros((3,3))
zero

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [54]:
# The random module in Numpy package contains many functions for generation of random numbers

In [56]:
a = np.random.rand(7)
print(a)
print("\n")
b = np.random.rand(4,3)
print(b)

[0.46771723 0.93164752 0.59842198 0.13431664 0.95997398 0.52594004
 0.84711285]


[[0.92939832 0.22668496 0.68216569]
 [0.54034641 0.88178766 0.54451972]
 [0.660038   0.16069104 0.91877295]
 [0.19842654 0.65165966 0.70484751]]


In [58]:
b = np.random.rand(4,3)
b

array([[0.71753164, 0.97289238, 0.8359521 ],
       [0.44751213, 0.5993584 , 0.98762739],
       [0.81083147, 0.17399707, 0.33821226],
       [0.15254165, 0.96492283, 0.80010857]])

In [59]:
sampl = np.random.uniform(1, 10, size=(3,4))
sampl

array([[2.63763601, 1.39965048, 6.46529941, 6.27202878],
       [9.0415822 , 9.13245642, 7.26902181, 3.18760043],
       [1.96580987, 1.78673421, 5.267235  , 7.54708337]])

In [87]:
a=np.array([1,2,3,4,5,6,7,8,9])  
x=a.reshape(3,3) 
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])